### ISSUE TITLE
@back280 Fragen zu setup

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/slime-mold-recording-setup#2]
siehe back280/Eingabe_Ausgabe_Code#2 by @back280 

Hi Fabian,

ich habe drei LEDs an meinem Board. 
Die letzte leuchtet dauerhaft. (LEDs sollten doch bei Bildaufnahme aufleuchten ?!?!)

Crontab funktioniert nicht. 
BIldaufnahme geht nur handisch und es wird ein Bild gemacht.

Workflow?
Wie synchronisierst Du die Daten zwischewn PI und Mac. 
Habe das mit der json Datei im Ansatz verstanden, dass die Daten synchronisiert werden sollen. 
Aber wie anbinden ?

**Comment by ff6347** [comment]
> ich habe drei LEDs an meinem Board. 
> Die letzte leuchtet dauerhaft. (LEDs sollten doch bei Bildaufnahme aufleuchten ?!?!)

Eigentlich ja. Mit der letzten Variante des Codes. Du musst deinen Schaltkreis nochmal überprüfen. Genauso musst du überprüfen ob du den Koppler richtig rum am Pi hast.

> Crontab funktioniert nicht. 

In deiner Teminal ausgabe steht:  

```
no modification made
```

Hast du nach dem Editieren den crontab nochmal aufgemacht? Ist deine Änderung noch drin?
In nano musst du "CTRL + O" zum speichern eingeben und "CTRL + X" zum verlassen.

gib mal ein:  

```
sudo crontab -l 
```

Das zeigt die aktiven cronjobs.

> Workflow?
> Wie synchronisierst Du die Daten zwischewn PI und Mac. 
> Habe das mit der json Datei im Ansatz verstanden, dass die Daten synchronisiert werden sollen.  
> Aber wie anbinden ?

Du musst den [atom](https://atom.io) editor verwenden und das [sftp development plugin](https://atom.io/packages/sftp-deployment) installieren. Wenn dann das json richtig eingerichtet ist (deine PI local hostname oder IP im json) dann sollte Atom bei jedem speichern die Daten übertragen.

**Comment by back280** [comment]
sudo crontab -l 

ergibt:
- \* \* \* \* /usr/bin/python /home/pi/fhp/slime_mold_recording_setup/camera-controller.py

**Comment by back280** [comment]
Pfad war natürlich nicht korrekt.

**Comment by back280** [comment]
#

**Comment by ff6347** [comment]
Cool das es jetzt geht.  
Was ist mit den LEDs?

**Comment by ff6347** [comment]
Ach ja. LEDs haben eine Richtung. Sie lassen Strom nur in einer Richtung durch. ;-)
